### ISSUE TITLE
'.' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by smilingOrange** [gunar/shellcheck#121]
PS D:\...\project_036> npm install --save-dev shellcheck@1.1.0
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code 1
npm ERR! path D:\....\project_036\node_modules\shellcheck
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c ./install.sh
npm ERR! '.' is not recognized as an internal or external command,
npm ERR! operable program or batch file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\...\AppData\Local\npm-cache\_logs\2023-04-29T07_01_35_368Z-debug-0.log

Previous versions are not installing.

**Comment by carlocorradini** [comment]
shellcheck versions before V2 are compatible only with Linux (and sometimes with MacOS) and not Linux.

**Comment by carlocorradini** [comment]
@smilingOrange Any update?

**Comment by PURUSHOTHAM-REDDY-N** [comment]
im also getting the same error . guys let me know if anyone resolve  this.

**Comment by carlocorradini** [comment]
@PURUSHOTHAM-REDDY-N 
Which version are you using?

**Comment by carlocorradini** [comment]
If no other information is provided, I will close this case.

**Comment by PURUSHOTHAM-REDDY-N** [comment]
@carlocorradini 

i am facing this issue on windows 11 
"shellcheck": "^1.1.0",

**Comment by carlocorradini** [comment]
Shellcheck V1 does not support Windows. Please upgrade to V2:
```sh
npm uninstall shellcheck
npm install shellcheck
```

**Comment by carlocorradini** [comment]
@PURUSHOTHAM-REDDY-N Please let me know if it works

**Comment by carlocorradini** [comment]
If I don't receive any feedback I'll close this issue since the version you are using is not the latest but V1.
