### ISSUE TITLE
"You are downloading ShellCheck from the wrong URL!

### ISSUE THREAD

**Issue by electrovir** [gunar/shellcheck#19]
```bash
npm install shellcheck
shellcheck
```

Results in the following being printed, even when passing in file paths to shellcheck:

```
You are downloading ShellCheck from the wrong URL!
Please update to the latest one:
https://github.com/koalaman/shellcheck/releases/download/latest/shellcheck-latest.darwin.x86_64.tar.xz

For more information, see:
https://github.com/koalaman/shellcheck/issues/1871
```

**Comment by ronkorving** [comment]
It's also failing the process with a non-zero exit code (and thus failing my `npm test`). Quite annoying.

**Comment by ronkorving** [comment]
It seems one challenge will be that there's no longer a "latest" URL.
The downloadable files are here, and are strictly versioned: https://github.com/koalaman/shellcheck/releases

**Comment by electrovir** [comment]
Awesome, got the updated the package and looks good. Thanks!
