### ISSUE TITLE
git repo needs tags

### ISSUE THREAD

**Issue by jasonkarns** [gunar/shellcheck#21]
Can git-tags be retroactively applied to each of the old releases? With this package being used as an npm dep, people will be receiving depfu/greenskeeper/dependabot type updates whenever the new versions are published. However, without git tags (and github releases) these bot updates are unable to provide any meaningful information about each version bump.

**Comment by gunar** [comment]
Thanks for the suggestion! Previous tags have been pushed. And I'll be creating releases as well from now on.
