### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by benmonro** [gunar/shellcheck#22]
after using `yarn add -D shellcheck` i get the following error:

```sh
[5/5] 🔨  Building fresh packages...
[10/16] ⠈ husky
[7/16] ⠈ ursa-optional
[11/16] ⠈ ejs
[4/16] ⠈ fsevents
error /node_modules/shellcheck: Command failed.
Exit code: 1
Command: ./install.sh
Arguments: 



```

**Comment by gunar** [comment]
Hey Ben,

I couldn't reproduce. Can you please try it on an empty repository? I would love to hear about it. There might be something we can do to prevent this problem from happening to other people too.

Cheers,
Gunar

**Comment by benmonro** [comment]
yeah on an empty repository it seems to work.  Sorry I can't provide any more info @gunar, we found another solution using hadolint.

Cheers
Ben

**Comment by gunar** [comment]
Good to know! Thanks for circling back. Today I learned about hadolint. Glad your problem is solved.

Cheers,
Gunar

**Comment by benmonro** [comment]
Sorry I couldn't be more help. 😔
