### ISSUE TITLE
Use `stable` over `latest`?

### ISSUE THREAD

**Issue by Pinjasaur** [gunar/shellcheck#25]
Related to discussion in #19 & #24 plus the code change in #20.

To put it succinctly: the package currently downloads the _latest build_, not the _latest release_. It's not immediately obvious, but Shellcheck treats `stable` as the most recent tagged release while `latest` is the most recent build. This is slightly different from the _latest_ release in the UI: https://github.com/koalaman/shellcheck/releases/latest

Examples:

- `latest`: https://github.com/koalaman/shellcheck/releases/download/latest/shellcheck-latest.darwin.x86_64.tar.xz 
- `stable`: https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.darwin.x86_64.tar.xz
- `v0.7.1`: https://github.com/koalaman/shellcheck/releases/download/v0.7.1/shellcheck-v0.7.1.darwin.x86_64.tar.xz

If you download these 3 (swapping out `darwin` for your appropriate architecture, if necessary) and extract the `shellcheck` executable it's apparent that the `latest` is much larger (over 3x file size, as I write this) and when `diff`-ed against `stable` or `v0.7.1`, is different. `stable` and `v0.7.1` are identical because, as I write this, `v0.7.1` is the _latest_ release.

This is causing some failing builds for me as there's some wacky behavior with whatever the `latest` build is doing (as I write this).

To keep the behavior as discussed in #24, swapping to `stable` would do the trick.

**Comment by gunar** [comment]
Hi @Pinjasaur, thank you for reporting. As suggested, I've moved us to the stable release, and published the change as a major/breaking version. Cheers.

**Comment by Pinjasaur** [comment]
Thanks @gunar! 🥂

**Comment by gunar** [comment]
No worries! Forgot to mention, this was released as `1.0.0`.

**Comment by Pinjasaur** [comment]
> No worries! Forgot to mention, this was released as `1.0.0`.

Looks good. The major version bump makes sense to me. Think there could be a short blurb in the README & release notes stating that you _almost certainly_ want to be on this new release as the previous release is effectively undefined behavior?

Thanks again.
