### ISSUE TITLE
Remove dependency on tar, xz-utils, and sh

### ISSUE THREAD

**Issue by gunar** [gunar/shellcheck#27]
Ideally this project should only depend on npm libraries.

**Comment by SRachamim** [comment]
Did you consider https://github.com/npm/node-tar?

**Comment by gunar** [comment]
I hadn't but it looks good!

**Comment by Rob4226** [comment]
FYI on FreeBSD it causes `tar: Error opening archive: Failed to open '/dev/sa0'`

**Comment by silverwind** [comment]
Problem with node xz extraction is, all modules in existance that can extract xz require native modules, which is another rabbit whole one might not want to go down.

I think it'd be best to convince the shellcheck author to provide `gz` which node can extract without additional dependencies.

**Comment by carlocorradini** [comment]
Please, see PR #34

**Comment by carlocorradini** [comment]
@gunar Can we close this?

**Comment by gunar** [comment]
Will be released in #34
