### ISSUE TITLE
Support for HTTP Proxy

### ISSUE THREAD

**Issue by karlismelderis** [gunar/shellcheck#28]
Seems that current implementation is ignoring HTTPS_PROXY/HTTP_PROXY ENV variables.
In our case install and calling download.js happens inside company network and Internet is accessible only via proxy hence the download fails.

**Comment by fgreinacher** [comment]
@gunar When are you planning to publish `1.1.0` to [NPM](https://www.npmjs.com/package/shellcheck)?

**Comment by gunar** [comment]
I've done it now. Thanks.

**Comment by fgreinacher** [comment]
Thanks, works like a charm!
