### ISSUE TITLE
Download a specific version

### ISSUE THREAD

**Issue by thernstig** [gunar/shellcheck#31]
We want to use this in CI, but if it always downloads the latest version when installing the npm dependencies, an unlucky user pushing a commit to CI might get a new version of shellcheck that creates new failures. This is not ideal.

Would it be possible that you add a env var that can be read to instead specify the version wanted?

**Comment by gunar** [comment]
I think that's a good idea. Would you like to open a PR for it? I'll be happy to review and merge it.

**Comment by thernstig** [comment]
I could if you want to, but would also not mind if you did it who knows the code :)

**Comment by carlocorradini** [comment]
Please, see PR #34 
If you want I can this feature...

**Comment by gunar** [comment]
This will soon be released in #34.

**Comment by carlocorradini** [comment]
@thernstig 

Create a script `shellcheck.js` under `scripts` directory that downloads ShellCheck:
```js
const shellcheck = require('shellcheck');

const SHELLCHECK_RELEASE = 'v0.9.0';
const SHELLCHECK_DESTINATION = `${ shellcheck.config.bindDir }/${ shellcheck.config.bin }`;

async function download() {
  try {
    const url = await buildURL({ release: SHELLCHECK_RELEASE });
    await shellcheck.download({ url, destination: SHELLCHECK_DESTINATION });
    shellcheck.logger.info(`Successfully downloaded ShellCheck ${ SHELLCHECK_RELEASE }`);
  } catch (err) {
    shellcheck.logger.error(`Error downloading ShellCheck ${ SHELLCHECK_RELEASE }: ${err}`);
  }
}

download();
```

Then, update `package.json` and add/update `prepare` script:
```json
{
  "scripts": {
    "prepare": "node scripts/shellcheck.js"
  }
}
```

This procedure can be simplified but for now it works 🥳

**Comment by thernstig** [comment]
@carlocorradini is that the new functionality you added? Can this be reflected in the README?

**Comment by carlocorradini** [comment]
Yes, maybe I'll simplify the programmatic available APIs :)

PS: To not interfere with the shellcheck binary the only safe way to configure this library is programmatic. If you have any idea :)
