### ISSUE TITLE
Error running "npx shellcheck" with v2.0.0 on Mac M1

### ISSUE THREAD

**Issue by rpastro** [gunar/shellcheck#56]
I'm getting the following error when running "npx shellcheck" with v2.0.0 on a Mac M1.   It works fine with v1.1.0.

```
[INFO ] ShellCheck binary not found or invalid, downloading to '/Users/rpastro/ngls/ngls/node_modules/shellcheck/bin/shellcheck'
[ERROR] Error downloading ShellCheck binary to '/Users/rpastro/ngls/ngls/node_modules/shellcheck/bin/shellcheck': Error: Architecture 'arm64' is not supported
/Users/rpastro/ngls/ngls/node_modules/shellcheck/build/utils/shellCheckArchitecture.js:24
        throw new errors_1.ArchitectureError();
              ^

ArchitectureError: Architecture 'arm64' is not supported
    at shellCheckArchitecture (/Users/rpastro/ngls/ngls/node_modules/shellcheck/build/utils/shellCheckArchitecture.js:24:15)
    at /Users/rpastro/ngls/ngls/node_modules/shellcheck/build/utils/buildURL.js:66:82
    at Generator.next (<anonymous>)
    at fulfilled (/Users/rpastro/ngls/ngls/node_modules/shellcheck/build/utils/buildURL.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.13.0
```

**Comment by carlocorradini** [comment]
Currently, there is no ShellCheck release that is natively compatibile with Apple arm64. Nevertheless, I know that with Rosetta 2 you can run x64 on arm64 (i.e. M series). I don't have a Mac Mx to try, but if you can ensure me that shellcheck x64 work without any problem on arm64 tomorrow I'll make a PR with the changes and @gunar will release V2.1.0.

**Comment by carlocorradini** [comment]
Currently, there is no ShellCheck release that is natively compatibile with Apple arm64. Nevertheless, I know that with Rosetta 2 you can run x64 on arm64 (i.e. M series). I don't have a Mac Mx to try, but if you can ensure me that shellcheck x64 work without any problem on arm64 tomorrow I'll make a PR with the changes and @gunar will release V2.1.0.

If you discover any further issues, please let us know 🥳🤯
Thanks 😎

**Comment by rpastro** [comment]
@carlocorradini   Thanks for the feedback.   I'm a little confused though. Which ShellCheck release is being downloaded with v1.1.0? Because that works fine. I only have a problem if update the shellcheck npm package to the new v2.0.0.

BTW, I'm running the latest Node.js 18.13.0.

**Comment by carlocorradini** [comment]
V1 ONLY downloads x64 architecture for ONLY Mac and Linux (i.e. platform that can run .sh scripts). Therefore, you have always used Rosetta 2 under the hood :)
With V2 has been added support for Windows and different architectures. The latter is checked before download that is why you have the error.


I misread your Node.js version :)

**Comment by rpastro** [comment]
I don't have Rosetta 2 installed though.  I have confirmed, however, that installed version is built for x86_64.  It's surprising that it works. 

```
rpastro@Rodrigos-MBP ngls % file node_modules/shellcheck/shellcheck-stable/shellcheck
node_modules/shellcheck/shellcheck-stable/shellcheck: Mach-O 64-bit executable x86_64
```

**Comment by carlocorradini** [comment]
I'm not an Apple expert but I think there is a translation layer somewhere; otherwise the binary should not work 😅

Any idea or?

**Comment by rpastro** [comment]
It seems Rosetta2 is automatically installed with Monterey. That explains why it works.

Could shellcheck npm be enhanced to download the x64 binary for MacOS until an arm64 version is available? Thanks.

**Comment by carlocorradini** [comment]
Yup tomorrow :)

**Comment by rpastro** [comment]
Awesome. Thanks.

**Comment by carlocorradini** [comment]
@rpastro See https://github.com/gunar/shellcheck/pull/59
