### ISSUE TITLE
Error downloading ShellCheck on Mac with v2.1.0

### ISSUE THREAD

**Issue by rpastro** [gunar/shellcheck#60]
@carlocorradini   Unfortunately v2 is still not working on Mac. 

```
rpastro@Rodrigos-MBP ngls % npx shellcheck
[INFO ] ShellCheck binary not found or invalid, downloading to '/Users/rpastro/ngls/ngls/node_modules/shellcheck/bin/shellcheck'
[INFO ] Downloading 'https://github.com/koalaman/shellcheck/releases/download/v0.9.0/shellcheck-v0.9.0.darwin.x86_64.tar.xz' to '/var/folders/wl/gf_x6dwn6gn083lnyknddz340000gn/T/5HUi69/shellcheck.download'
[INFO ] Extracting '/var/folders/wl/gf_x6dwn6gn083lnyknddz340000gn/T/5HUi69/shellcheck.download' to '/var/folders/wl/gf_x6dwn6gn083lnyknddz340000gn/T/5HUi69'
dyld[92369]: missing symbol called
zsh: abort      npx shellcheck
```

Has anything changed in v2.1.0 compared to v1.1.0 on how the downloaded file is extracted?

**Comment by carlocorradini** [comment]
Try:
```sh
rm -rf node_modules
npm install
```

If does not work: https://gist.github.com/adrienjoly/e29a6e73fb7e701eefd80ff9bde9abeb

I think the error is due to the decompression libraries that depend on native code.

**Comment by carlocorradini** [comment]
@rpastro See [this](https://github.com/addaleax/lzma-native/issues/127)

**Comment by carlocorradini** [comment]
I hate `.tar.xz` compression...
Moreover, there are no good libraries in Node.js that handle decompression easily and with a wide support (if you have a suggestion 🤯).
The only way to solve this is detect `darwin arm64` and use the "native" `tar`. This solution is **very very ugly** but is the only one I came up with until [this](https://github.com/addaleax/lzma-native/issues/127) is fixed :/

Let me know what you think 😥

**Comment by rpastro** [comment]
I tried overriding the lzma-native library back to 7.0.1 and it seems to have solved the issue for Mac M1. I don't know, however, if this could cause issues for other deployments.
```
  "overrides": {
    "@felipecrs/decompress-tarxz@^4.0.0": {
        "lzma-native": "7.0.1"
    }
  },
```

```
rpastro@Rodrigos-MBP ngls % npm list lzma-native
ngls@1.1.7800-SNAPSHOT /Users/rpastro/ngls/ngls
└─┬ shellcheck@2.1.0
  └─┬ @felipecrs/decompress-tarxz@4.0.0 overridden
    └── lzma-native@7.0.1 overridden
```

How were you decompressing the tar files in v1.1.0?

**Comment by carlocorradini** [comment]
Wow thanks!
The only problem with older versions I noticed is on windows 😅
Thanks again for using your M1 as a testing platform.

**Comment by carlocorradini** [comment]
I've tested `lzma-native": "7.0.1"` on Linux x64 and Windows x64 and it is working

**Comment by carlocorradini** [comment]
@rpastro
See [this](https://github.com/kevva/decompress-tarxz/pull/14#issuecomment-1414456385) for more information.
I've asked to publish a version with `lzma-native": "7.0.1"` under a different tag name.
I'm hoping for a quick response.

**Comment by carlocorradini** [comment]
I apologize for the inconvenience, but as far as I can see, supporting Apple Silicon is not simple...

**Comment by rpastro** [comment]
Thanks @carlocorradini.  I appreciate  your prompt responses.

**Comment by felipecrs** [comment]
Guys... let me help you out. We (re)package all ShellCheck binaries in tar.gz format for use in the VSCode ShellCheck extension: https://github.com/vscode-shellcheck/shellcheck-binaries/releases

It includes the one from Apple M1.

I'd suggest downloading from there instead.

**Comment by carlocorradini** [comment]
I'm crying 😭

**Comment by carlocorradini** [comment]
@felipecrs 
A dummy question: why not also including Windows?

**Comment by felipecrs** [comment]
The Windows one is already in zip format, so we don't bother. But I don't mind, if you want to add it to CI too, let's do it.

**Comment by carlocorradini** [comment]
@felipecrs 
If you are not bothered by it.
It is simply for convenience (everything in one place/repo and format).
It also allows to remove the dependency `decompress-unzip`.
Thank you one again

**Comment by felipecrs** [comment]
Here's the script, please send a PR. It should be simple. I can merge it quickly for you.

https://github.com/vscode-shellcheck/shellcheck-binaries/blob/main/scripts/download_and_archive.sh

**Comment by felipecrs** [comment]
Did you start working on it already?

**Comment by carlocorradini** [comment]
Yup, working on it :)

**Comment by carlocorradini** [comment]
@felipecrs Done

**Comment by carlocorradini** [comment]
@rpastro Working on it
You will have native binaries

**Comment by carlocorradini** [comment]
@rpastro 
See PR #21

**Comment by rpastro** [comment]
@carlocorradini.  I'll test it on the M1 as soon as the new version is released. Thanks a lot for your support.

**Comment by rpastro** [comment]
@carlocorradini  v2.2.0 worked perfectly. Thanks again.
