### ISSUE TITLE
v2 regression: downloading binary via proxy no longer supported

### ISSUE THREAD

**Issue by nejch** [gunar/shellcheck#61]
In 2021 @fgreinacher added support for downloading the binary via proxy: https://github.com/gunar/shellcheck/pull/32

https://github.com/gunar/shellcheck/pull/34 completely rewrote this but forgot to include proxy support.

Seems to be a common pattern in node wrapper rewrites, the same happened in https://github.com/editorconfig-checker/editorconfig-checker.javascript/issues/394 recently. Maybe some tests for these things would make sense :)

**Comment by carlocorradini** [comment]
@nejch 
Proxy support is still available, see [utils/request.ts](https://github.com/gunar/shellcheck/blob/main/src/utils/request.ts#L1).
It is configured with the basic setup `import 'global-agent/bootstrap'` where you need to pass the environment variable `GLOBAL_AGENT_HTTP_PROXY` to set the proxy address (global agent).
Moreover, the old approach (as far as I can see from the offical [documentation](https://github.com/gajus/global-agent#setup-proxy-using-createglobalproxyagent)) does not instantiate a global agent (returned `globalProxyAgent ` is discarded/unused) therefore it does not have any effect.

Please keep in mind that these are merely my interpretations of the [official documentation](https://github.com/gajus/global-agent). If I'm missing something or there is a misconfiguration please help me 🙏🥳

**Comment by nejch** [comment]
@carlocorradini thanks for the quick response!

Ah, I see, sorry I wasn't too familiar with global-agent then. Looks like a fairly non-standard way of doing it with the `GLOBAL_AGENT_` prefix, most tools respect `https_proxy`, `http_proxy`, `no_proxy` etc - see https://about.gitlab.com/blog/2021/01/27/we-need-to-talk-no-proxy/.


So I think the old approach simply instantiated it without this prefix (using the empty namespace) so that it respected  standard proxy variables.  It definitely worked as we just started seeing issues with proxy downloads after bumping to v2 :)

Looks like a quick fix by just adding that line again to restore the old behavior if you're not against it, I can open a little PR for that.

**Comment by carlocorradini** [comment]
@nejch 
No problem.
New:
```ts
import { bootstrap } from 'global-agent';

bootstrap({ environmentVariableNamespace: '' });
```

Ok for you?

**Comment by carlocorradini** [comment]
@nejch Do you have an idea for any test?

**Comment by carlocorradini** [comment]
@nejch See PR #21

**Comment by nejch** [comment]
Thanks @carlocorradini for the quick PR! If you want to test the behavior, I see that global-agent itself has a mock http proxy for its tests (see [`createProxyServer` here](https://github.com/gajus/global-agent/blob/master/test/global-agent/factories/createGlobalProxyAgent.ts#L184-L196)) but that's probably overkill here.

Since you use `bootstrap` maybe you can just check that `global.GLOBAL_AGENT` has the correct `HTTPS_PROXY` / `HTTP_PROXY` / `NO_PROXY` values set when environment variables are present? It will at least signal to anyone making changes that the proxy is being used this way :)
